In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('/home/ayush/Downloads/archive/covid_vaccine_statewise.csv')
df.head()

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
0,16/01/2021,India,48276.0,3455.0,2957.0,48276.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,23757.0,24517.0,2.0,48276.0
1,17/01/2021,India,58604.0,8532.0,4954.0,58604.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,27348.0,31252.0,4.0,58604.0
2,18/01/2021,India,99449.0,13611.0,6583.0,99449.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,41361.0,58083.0,5.0,99449.0
3,19/01/2021,India,195525.0,17855.0,7951.0,195525.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,81901.0,113613.0,11.0,195525.0
4,20/01/2021,India,251280.0,25472.0,10504.0,251280.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,98111.0,153145.0,24.0,251280.0

In [4]:
df.isnull().sum()

Updated On                                0
State                                     0
Total Doses Administered                224
Sessions                                224
 Sites                                  224
First Dose Administered                 224
Second Dose Administered                224
Male (Doses Administered)               384
Female (Doses Administered)             384
Transgender (Doses Administered)        384
 Covaxin (Doses Administered)           224
CoviShield (Doses Administered)         224
Sputnik V (Doses Administered)         4850
AEFI                                   2407
18-44 Years (Doses Administered)       6143
45-60 Years (Doses Administered)       6143
60+ Years (Doses Administered)         6143
18-44 Years(Individuals Vaccinated)    4112
45-60 Years(Individuals Vaccinated)    4111
60+ Years(Individuals Vaccinated)      4111
Male(Individuals Vaccinated)           7685
Female(Individuals Vaccinated)         7685
Transgender(Individuals Vaccinated)    7685
Total Individuals Vaccinated           1926
dtype: int64

In [5]:
df.shape

(7845, 24)

In [6]:
df['State'].unique()

array(['India', 'Andaman and Nicobar Islands', 'Andhra Pradesh',
       'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh',
       'Chhattisgarh', 'Dadra and Nagar Haveli and Daman and Diu',
       'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh',
       'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Ladakh',
       'Lakshadweep', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
       'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry',
       'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana',
       'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal'],
      dtype=object)

In [7]:
df.sort_values(['State'])

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
423,15/08/2021,Andaman and Nicobar Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
287,01/04/2021,Andaman and Nicobar Islands,22608.0,1700.0,17.0,17435.0,5173.0,10347.0,7088.0,0.0,...,NaN,NaN,NaN,5123.0,7806.0,4504.0,NaN,NaN,NaN,17435.0
286,31/03/2021,Andaman and Nicobar Islands,21938.0,1300.0,12.0,16798.0,5140.0,9989.0,6809.0,0.0,...,NaN,NaN,NaN,5076.0,7495.0,4225.0,NaN,NaN,NaN,16798.0
285,30/03/2021,Andaman and Nicobar Islands,21840.0,1600.0,16.0,16701.0,5139.0,9939.0,6762.0,0.0,...,NaN,NaN,NaN,5070.0,7465.0,4164.0,NaN,NaN,NaN,16701.0
284,29/03/2021,Andaman and Nicobar Islands,21357.0,1600.0,15.0,16292.0,5065.0,9709.0,6583.0,0.0,...,NaN,NaN,NaN,5036.0,7360.0,3894.0,NaN,NaN,NaN,16292.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7706,30/03/2021,West Bengal,5323718.0,650031.0,3453.0,4671332.0,652386.0,2613576.0,2057218.0,538.0,...,NaN,NaN,NaN,729498.0,1595242.0,2345801.0,NaN,NaN,NaN,4671332.0
7707,31/03/2021,West Bengal,5467439.0,521560.0,2608.0,4798424.0,669015.0,2676605.0,2121264.0,555.0,...,NaN,NaN,NaN,733567.0,1646753.0,2417309.0,NaN,NaN,NaN,4798424.0
7708,01/04/2021,West Bengal,5614451.0,527960.0,2701.0,4932709.0,681742.0,2742833.0,2189310.0,566.0,...,NaN,NaN,NaN,737390.0,1728144.0,2466374.0,NaN,NaN,NaN,4932709.0
7710,03/04/2021,West Bengal,5967900.0,564020.0,3077.0,5260046.0,707854.0,2902501.0,2356946.0,599.0,...,NaN,NaN,NaN,744699.0,1937086.0,2577444.0,NaN,NaN,NaN,5260046.0
7844,15/08/2021,West Bengal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
statewise_vaccination=df.groupby('State')['Total Individuals Vaccinated'].sum().to_frame('Total Individuals Vaccinated')
statewise_vaccination

                                          Total Individuals Vaccinated
State
Andaman and Nicobar Islands                               8.102125e+06
Andhra Pradesh                                            5.645911e+08
Arunachal Pradesh                                         2.108156e+07
Assam                                                     2.397691e+08
Bihar                                                     6.608479e+08
Chandigarh                                                1.973150e+07
Chhattisgarh                                              4.353092e+08
Dadra and Nagar Haveli and Daman and Diu                  1.135860e+07
Delhi                                                     3.057372e+08
Goa                                                       3.211478e+07
Gujarat                                                   1.078261e+09
Haryana                                                   3.637547e+08
Himachal Pradesh                                          1.504916e+08
India                                                     1.346231e+10
Jammu and Kashmir                                         2.037598e+08
Jharkhand                                                 2.891507e+08
Karnataka                                                 8.685235e+08
Kerala                                                    6.208252e+08
Ladakh                                                    9.466289e+06
Lakshadweep                                               2.124715e+06
Madhya Pradesh                                            7.718640e+08
Maharashtra                                               1.403075e+09
Manipur                                                   2.665426e+07
Meghalaya                                                 2.720527e+07
Mizoram                                                   2.057245e+07
Nagaland                                                  1.762450e+07
Odisha                                                    5.105198e+08
Puducherry                                                1.776065e+07
Punjab                                                    2.875444e+08
Rajasthan                                                 1.141163e+09
Sikkim                                                    1.613675e+07
Tamil Nadu                                                5.437461e+08
Telangana                                                 3.933718e+08
Tripura                                                   9.379244e+07
Uttar Pradesh                                             1.200575e+09
Uttarakhand                                               1.747382e+08
West Bengal                                               9.250227e+08

In [16]:
first_dose=df[['State','First Dose Administered']].groupby('State').sum()
first_dose

                                          First Dose Administered
State
Andaman and Nicobar Islands                          1.642585e+07
Andhra Pradesh                                       1.232861e+09
Arunachal Pradesh                                    4.900498e+07
Assam                                                5.856002e+08
Bihar                                                1.470503e+09
Chandigarh                                           4.470310e+07
Chhattisgarh                                         7.960029e+08
Dadra and Nagar Haveli and Daman and Diu             3.359506e+07
Delhi                                                6.243395e+08
Goa                                                  7.599137e+07
Gujarat                                              2.131646e+09
Haryana                                              7.557984e+08
Himachal Pradesh                                     3.162940e+08
India                                                2.826214e+10
Jammu and Kashmir                                    4.101018e+08
Jharkhand                                            6.036737e+08
Karnataka                                            1.873330e+09
Kerala                                               1.193845e+09
Ladakh                                               1.780925e+07
Lakshadweep                                          4.363655e+06
Madhya Pradesh                                       1.796605e+09
Maharashtra                                          2.784364e+09
Manipur                                              6.740957e+07
Meghalaya                                            6.261597e+07
Mizoram                                              4.787308e+07
Nagaland                                             4.241077e+07
Odisha                                               1.032633e+09
Puducherry                                           4.134686e+07
Punjab                                               5.843466e+08
Rajasthan                                            2.201044e+09
Sikkim                                               3.698093e+07
Tamil Nadu                                           1.288533e+09
Telangana                                            8.803206e+08
Tripura                                              1.926897e+08
Uttar Pradesh                                        2.788411e+09
Uttarakhand                                          3.631914e+08
West Bengal                                          1.796450e+09

In [17]:
second_dose=df[['State','Second Dose Administered']].groupby('State').sum()
second_dose

                                          Second Dose Administered
State
Andaman and Nicobar Islands                           4.118554e+06
Andhra Pradesh                                        3.588176e+08
Arunachal Pradesh                                     1.193232e+07
Assam                                                 1.307888e+08
Bihar                                                 2.707906e+08
Chandigarh                                            1.159374e+07
Chhattisgarh                                          1.721204e+08
Dadra and Nagar Haveli and Daman and Diu              4.594416e+06
Delhi                                                 1.882189e+08
Goa                                                   1.619817e+07
Gujarat                                               6.004184e+08
Haryana                                               1.586561e+08
Himachal Pradesh                                      7.383858e+07
India                                                 6.759621e+09
Jammu and Kashmir                                     8.595165e+07
Jharkhand                                             1.221211e+08
Karnataka                                             4.271872e+08
Kerala                                                3.640488e+08
Ladakh                                                5.453762e+06
Lakshadweep                                           1.056446e+06
Madhya Pradesh                                        3.169330e+08
Maharashtra                                           7.128811e+08
Manipur                                               1.185815e+07
Meghalaya                                             1.216663e+07
Mizoram                                               9.998418e+06
Nagaland                                              9.204637e+06
Odisha                                                2.513028e+08
Puducherry                                            8.608859e+06
Punjab                                                1.211210e+08
Rajasthan                                             4.917030e+08
Sikkim                                                9.723640e+06
Tamil Nadu                                            2.906706e+08
Telangana                                             1.981529e+08
Tripura                                               6.527014e+07
Uttar Pradesh                                         5.544351e+08
Uttarakhand                                           1.000850e+08
West Bengal                                           5.861469e+08

In [19]:
statewise_vaccination=df[['State','Total Individuals Vaccinated']].groupby('State').sum()
statewise_vaccination

                                          Total Individuals Vaccinated
State
Andaman and Nicobar Islands                               8.102125e+06
Andhra Pradesh                                            5.645911e+08
Arunachal Pradesh                                         2.108156e+07
Assam                                                     2.397691e+08
Bihar                                                     6.608479e+08
Chandigarh                                                1.973150e+07
Chhattisgarh                                              4.353092e+08
Dadra and Nagar Haveli and Daman and Diu                  1.135860e+07
Delhi                                                     3.057372e+08
Goa                                                       3.211478e+07
Gujarat                                                   1.078261e+09
Haryana                                                   3.637547e+08
Himachal Pradesh                                          1.504916e+08
India                                                     1.346231e+10
Jammu and Kashmir                                         2.037598e+08
Jharkhand                                                 2.891507e+08
Karnataka                                                 8.685235e+08
Kerala                                                    6.208252e+08
Ladakh                                                    9.466289e+06
Lakshadweep                                               2.124715e+06
Madhya Pradesh                                            7.718640e+08
Maharashtra                                               1.403075e+09
Manipur                                                   2.665426e+07
Meghalaya                                                 2.720527e+07
Mizoram                                                   2.057245e+07
Nagaland                                                  1.762450e+07
Odisha                                                    5.105198e+08
Puducherry                                                1.776065e+07
Punjab                                                    2.875444e+08
Rajasthan                                                 1.141163e+09
Sikkim                                                    1.613675e+07
Tamil Nadu                                                5.437461e+08
Telangana                                                 3.933718e+08
Tripura                                                   9.379244e+07
Uttar Pradesh                                             1.200575e+09
Uttarakhand                                               1.747382e+08
West Bengal                                               9.250227e+08